---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: hello-node
          image: hello-node:v2
          ports:
            - containerPort: 8080
 

